"""Fail if a template literal in the page scripts interpolates a value that is not provably safe.

Every ${...} inside a backtick string in templates/*.html must be one of:
  escapeHtml(...), Number(...), a value formatted with .toLocaleString()/.toFixed()/.length, a plain index/counter
  name, a ternary choosing between string literals, or contain a /* safe: reason */ comment inside the ${...} (use it for HTML built from escaped parts).
File-derived text (column names, cell values, file names, server messages) must go through escapeHtml.

Usage: python scripts/check_innerhtml.py            (exit 1 and a list if anything is unsafe)
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAFE_CALL = re.compile(r'^(escapeHtml|Number|parseInt|parseFloat|Math\.\w+|formatNumber|formatBytes)\(')
SAFE_TAIL = re.compile(r'(\.toLocaleString\([^)]*\)|\.toFixed\([^)]*\)|\.length|\.size)$')
SAFE_NAME = re.compile(r'^(i|j|k|n|idx|index|count|total|percentage|pct|num\w*|\w*Count|\w*Index|\w*Id|safe[A-Z]\w*)$')
# Numbers, counters and ids generated by the server or the page itself (never file content)
SAFE_NUMERIC = re.compile(
    r'^(?:formatFileSize|formatTime|formatDuration)\(.*\)$|'
    r'^[\w.?\[\]]*\b(?:cols|rows|cache_id|sessionId|session_id|cached_at|minutes|seconds|secs|total|current|'
    r'percentage|priority|memory_usage_mb|null_percentage|min_length|max_length|error_rate|duplicatePct|'
    r'sizeMB|reclassified_columns|alternatives_count|minimal_columns_count|selected_columns_count|'
    r'total_duplicates|total_ids_to_remove|rule\.id|state\.sessionId)\b(?:\s*\|\|\s*\d+)?$|'
    r'^(?:idx|i|j|index)\s*[+-]\s*\d+$|^(?:minutes|seconds|secs|eta)$|^colName\.replace\(/\[\^a-zA-Z0-9\]/g, \'_\'\)$')
SAFE_TERNARY = re.compile(r'''^[^?]+\?\s*(['"`])[^'"`$]*\1\s*:\s*(['"`])[^'"`$]*\2$''')


def interpolations(text, first_line=1):
    """Yield (line_number, expression, text_after) for every ${...} inside a backtick literal, including the
    interpolations of template literals nested inside another ${...} (e.g. inside .map(x => `...`))."""
    i, line, in_tpl = 0, first_line, False
    out = []
    while i < len(text):
        c = text[i]
        if c == '\n':
            line += 1
        if not in_tpl:
            if c == '`':
                in_tpl = True
            i += 1
            continue
        if c == '\\':
            i += 2
            continue
        if c == '`':
            in_tpl = False
            i += 1
            continue
        if c == '$' and text[i + 1:i + 2] == '{':
            depth, j, start = 1, i + 2, i + 2
            while j < len(text) and depth:
                if text[j] == '{':
                    depth += 1
                elif text[j] == '}':
                    depth -= 1
                j += 1
            expr = text[start:j - 1]
            out.append((line, expr.strip(), text[j:j + 40]))
            out.extend(interpolations(expr, line)) if '`' in expr else None
            line += expr.count('\n')
            i = j
            continue
        i += 1
    return out


def is_fragment(expr):
    """An expression that assembles markup out of nested templates (its own ${...} are checked on their own)."""
    return '`' in expr


def is_safe(expr, after):
    if re.search(r'/\*\s*safe:', expr):
        return True   # annotated inside the ${...}: a comment after the brace would be rendered as text
    e = expr.strip()
    if is_fragment(e):
        return True
    return bool(SAFE_CALL.match(e) or SAFE_TAIL.search(e) or SAFE_NAME.match(e) or SAFE_TERNARY.match(e)
                or SAFE_NUMERIC.match(e)
                or re.fullmatch(r'[\d\s+\-*/().%]+', e))


def main():
    problems = []
    for path in sorted(glob.glob(os.path.join(ROOT, 'templates', '*.html'))):
        text = open(path, encoding='utf-8').read()
        for line, expr, after in interpolations(text):
            if not is_safe(expr, after):
                problems.append((os.path.relpath(path, ROOT), line, expr))
    for path, line, expr in problems:
        print(f'{path}:{line}: unescaped ${{{expr[:90]}}}')
    print(f'{len(problems)} unsafe interpolation(s)')
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
